import Head from 'next/head'
import {Header} from '../components/Head'
import { MainComponent } from './styles'

export default function Home() {
  return (
    <MainComponent>
      <Head>
        <title>My Organization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>


      <footer>
      </footer>
    </MainComponent>
  )
}
